project/src/templatesandmoe/modules/orders/models.py
import datetime

class CardPayment:
    def __init__(self, name, number, expiration_month, expiration_year, cvc):
        self.name = name
        self.number = number
        self.expiration = datetime.date(expiration_year, month=expiration_month, day=1)
        self.cvc = cvc

project/src/templatesandmoe/modules/users/models.py
import bcrypt
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Table, Column, Integer, String, ForeignKey
from templatesandmoe import db, db_session

Base = declarative_base()


class User(Base):
    __tablename__ = 'Users'

    user_id = Column(Integer, primary_key=True)
    username = Column(String)
    password = Column(String)
    first_name = Column(String)
    last_name = Column(String)
    email = Column(String)
    permissions = Column(Integer)

    @property
    def full_name(self):
        return self.first_name + ' ' + self.last_name

    def set_password(self, new_password):
        encoded_new_password = new_password.encode('utf-8')
        hashed_password = bcrypt.hashpw(encoded_new_password, bcrypt.gensalt())

        self.password = hashed_password

    def create(self):
        db_session.add(self)

        db_session.commit()

        return self

    def save(self):
        db_session.add(self)
        db_session.commit()

        return self

project/src/templatesandmoe/modules/admin/forms/user.py
from flask.ext.wtf import Form
from wtforms.fields import StringField, PasswordField
from wtforms.validators import DataRequired, Email


class UserForm(Form):
    username = StringField('Username', validators=[DataRequired(message='Username is required.')])
    password = PasswordField('Password')
    first_name = StringField('First Name')
    last_name = StringField('Last Name')
    email = StringField('Email')
    permissions = StringField('Permissions', default=0)

project/src/templatesandmoe/modules/main/forms/payment_information.py
from flask.ext.wtf import Form
from wtforms.fields import StringField, PasswordField, SelectField
from wtforms.validators import DataRequired, Email
import datetime

def month_choices():
    choices = []
    for i in range(1, 13):
        choices.append((i,i))

    return choices

def year_choices():
    choices = []
    now = datetime.datetime.now()
    current_year = now.year

    for i in range(current_year, current_year + 11):
        choices.append((i,i))
    return choices

class PaymentInformationForm(Form):
    name = StringField('Name on Card', validators=[DataRequired(message='Name on card is required.')])
    number = StringField('Card Number', validators=[DataRequired('Card number is required.')])

    expiration_month = SelectField('Month', choices=month_choices(), coerce=int, validators=[DataRequired('Expiration month is required.')])
    expiration_year = SelectField('Year', choices=year_choices(), coerce=int, validators=[DataRequired('Expiration year is required.')])

    cvc = StringField('CVC/CW', validators=[DataRequired('Security code is required.')])

project/src/templatesandmoe/modules/items/controllers.py
from flask import abort, Blueprint, flash, request, render_template, redirect, session
from templatesandmoe.modules.core.pagination import Pagination
from templatesandmoe import db_session
from templatesandmoe.modules.items.service import ItemsService
from templatesandmoe.modules.categories.service import CategoriesService
from templatesandmoe.modules.ratings.service import RatingsService
from templatesandmoe.modules.auctions.service import AuctionsService
from templatesandmoe.modules.tags.service import TagsService

itemsModule = Blueprint('items', __name__)
items = ItemsService(database=db_session)
categories = CategoriesService(database=db_session)
ratings = RatingsService(database=db_session)
auctions = AuctionsService(database=db_session)
tags = TagsService(database=db_session)

"""
    Show all templates
"""
@itemsModule.route('/templates/', defaults={ 'page': 1, 'category': 0 })
@itemsModule.route('/templates/<int:category>/page/<int:page>')
def all_templates(category, page):
    price_start = request.args.get('price-start')
    price_end = request.args.get('price-end')
    search = request.args.get('search')

    templates, count = items.get_filtered_templates(page=page,
                                                    templates_per_page=15,
                                                    category=category,
                                                    price_start=price_start,
                                                    price_end=price_end,
                                                    search=search)
    pagination = Pagination(page, 15, count)
    child_categories = categories.get_children(root_category=category)

    breadcrumb = None
    if category > 0:
        breadcrumb = categories.get_path_to_root(category)

    return render_template('main/templates.html',
                           templates=templates,
                           pagination=pagination,
                           categories=child_categories,
                           breadcrumb=breadcrumb,
                           category=category,
                           price_start=price_start,
                           price_end=price_end,
                           search=search)


"""
    Show a single template
"""
@itemsModule.route('/templates/<int:item_id>')
def single_template(item_id):
    template = items.get_template_by_id(item_id)
    breadcrumb = categories.get_path_to_root(template.category_id)
    item_tags = tags.get_tags_for_item(item_id)
    rating = ratings.get_average_by_template_id(template.template_id)

    # if the user is logged in, determine if they have already rated this template.
    user_rating = None
    if session.get('user_id'):
        user_rating = ratings.get_rating_for_template_by_user(template.template_id, session.get('user_id'))

    return render_template('main/template.html',
                           breadcrumb=breadcrumb,
                           template=template,
                           rating=rating,
                           user_rating=user_rating,
                           item_tags=item_tags)


"""
    Create or update a rating for a template
"""
@itemsModule.route('/templates/<int:item_id>/ratings', methods=['POST'])
def update_rating(item_id):
    if session.get('user_id'):
        rating = request.form.get('rating')
        user_rating = ratings.get_rating_for_template_by_user(item_id, session.get('user_id'))

        if user_rating is not None:
            ratings.update_rating(item_id, session.get('user_id'), rating)
        else:
            ratings.add_rating(item_id, session.get('user_id'), rating)

        return redirect(request.referrer)
    else:
        return redirect('/login')


"""
    Show all services
"""
@itemsModule.route('/services/', defaults={'page': 1})
@itemsModule.route('/services/page/<int:page>')
def services(page):
    auctions, count = items.get_filtered_services(page, services_per_page=15)
    pagination = Pagination(page, 15, count)

    return render_template('main/services.html',
                           auctions=auctions,
                           pagination=pagination)


"""
    Show single service
"""
@itemsModule.route('/services/<int:item_id>')
def single_service(item_id):
    service = items.get_service_by_id(item_id)
    if service is not None:
        bids = auctions.get_bids_for_service(service.service_id)
        has_ended = auctions.ended(service)

        return render_template('main/service.html',
                               service=service,
                               bids=bids,
                               has_ended=has_ended)
    else:
        abort(404)


"""
    Add a bid to a service
"""
@itemsModule.route('/services/<int:item_id>/bids', methods=['POST'])
def place_bid(item_id):
    user_id = session.get('user_id')
    amount = request.form.get('amount')

    if user_id:
        service = items.get_service_by_id(item_id)
        if not auctions.ended(service):
            highest_bid = auctions.get_highest_bid(service.service_id)

            if highest_bid is None:
                bid_check_amount = service.start_price
            else:
                bid_check_amount = highest_bid.amount

            # Make sure bid amount is a valid currency amount
            try:
                amount = float("{0:.2f}".format(float(amount)))
            except:
                flash('Bid must be a valid amount.', category='bid')
                return redirect(request.referrer)

            # Don't allow bidding if current user is the owner of the service
            # or if the current user is currently the highest bidder (only if bids exist)
            if service.user_id != user_id and (highest_bid is None or highest_bid.user_id != user_id):

                # if there is a highest bid, make sure the bid amount is greater than it
                if amount > bid_check_amount:
                    if amount - bid_check_amount >= 2:
                        auctions.place_bid(service.service_id, user_id, amount)
                        flash('Successfully placed bid', category='bid_placed')
                    else:
                        flash('Bid must be $2.00 greater than the highest bid.', category='bid')
                    return redirect(request.referrer)
                else:
                    flash('Bid amount must be greater than highest bid.', category='bid')
                    return redirect(request.referrer)
            else:
                flash('You already have the highest bid.', category='bid')
                return redirect(request.referrer)
        else:
            flash('This auction has ended already.')
            return redirect(request.referrer)
    else:
        return redirect('/login')

project/src/templatesandmoe/modules/main/controllers.py
import os
from flask import Blueprint, request, render_template, redirect, session, flash
from config import TEMPLATES_DATA_PATH
from templatesandmoe import db_session, hashids
from templatesandmoe.modules.items.service import ItemsService
from templatesandmoe.modules.items.forms import AddTemplateForm, AddServiceForm
from templatesandmoe.modules.main.forms.payment_information import PaymentInformationForm
from templatesandmoe.modules.orders.service import OrdersService
from templatesandmoe.modules.orders.models import CardPayment
from templatesandmoe.modules.categories.service import CategoriesService
from templatesandmoe.modules.auctions.service import AuctionsService
from templatesandmoe.modules.tags.service import TagsService
from templatesandmoe.modules.users.service import UsersService
from templatesandmoe.modules.reporting.service import ReportingService

mainModule = Blueprint('main', __name__)
items = ItemsService(database=db_session)
orders = OrdersService(database=db_session)
categories = CategoriesService(database=db_session)
auctions = AuctionsService(database=db_session)
tags = TagsService(database=db_session)
users = UsersService(database=db_session)
reports = ReportingService(database=db_session)


@mainModule.route('/', methods=['GET'])
def home():
    latest_templates = items.get_latest_templates(4)
    return render_template("main/home.html", latest_templates=latest_templates)


@mainModule.route('/account')
def account():
    if session.get('user_id'):
        user_id = session.get('user_id')
        users_bid_services = auctions.get_services_user_bid_on(user_id)
        won_bids = auctions.get_won_bids_by_user(user_id)
        users_services = items.get_services_by_user_id(user_id)

        return render_template("main/account.html",
                               users_bid_services=users_bid_services,
                               won_bids=won_bids,
                               users_services=users_services)
    else:
        return redirect('/login')


@mainModule.route('/account/templates')
def account_templates():
    user_id = session.get('user_id')
    if user_id:
        templates = reports.item_sales_report_for_user(user_id)

        return render_template('main/account_items.html',
                               items=templates)
    else:
        return redirect('/login')


@mainModule.route('/account/orders')
def account_orders():
    if session.get('user_id'):
        templates = orders.get_orders_by_user(session.get('user_id'))

        return render_template('main/account_orders.html',
                               orders=templates)
    else:
        return redirect('/login')


@mainModule.route('/orders/<string:transaction_id>')
def order_summary(transaction_id):
    decoded_id = hashids.decode(transaction_id)
    transaction = orders.get_order_by_id(decoded_id)

    # make sure the currently logged in user owns this order
    if transaction[0].user_id == session.get('user_id'):
        return render_template('main/order_summary.html', transaction=transaction, order_id=transaction_id)
    else:
        return redirect('/login')


@mainModule.route('/order/template/<int:item_id>', methods=['GET', 'POST'])
def order_item(item_id):
    if session.get('user_id'):
        template = items.get_template_by_id(item_id)

        if template is not None:
            payment_form = PaymentInformationForm()

            if payment_form.validate_on_submit():
                card = CardPayment(payment_form.name.data,
                                   payment_form.number.data,
                                   payment_form.expiration_month.data,
                                   payment_form.expiration_year.data,
                                   payment_form.cvc.data)
                transaction_id = orders.create_order(session.get('user_id'), card, [template.item_id])
                encoded_transaction_id = hashids.encode(transaction_id)
                return redirect('/orders/' + encoded_transaction_id)
            else:
                return render_template('main/order.html', template=template, form=payment_form)
        else:
            return redirect('/')
    else:
        return redirect('/login')


@mainModule.route('/sell/template', methods=['GET', 'POST'])
def sell_template():
    if session.get('user_id'):
        template_form = AddTemplateForm()

        all_categories = categories.get_all()
        categories_select_datasource = []
        for cat in all_categories:
            categories_select_datasource.append((cat.category_id, cat.name))
        template_form.category.choices = categories_select_datasource

        all_tags = tags.get_all()

        if template_form.validate_on_submit():

            # Insert the template into the database, then create a folder for it in templates_data
            try:
                item_id = items.add_template(
                    session.get('user_id'),
                    template_form.name.data,
                    template_form.price.data,
                    template_form.description.data,
                    template_form.category.data)

                tags.create_custom_tags_for_item(template_form.custom_tags.data.split(','), item_id)
                tags.add_tags_to_item(template_form.tags.data.split(','), item_id)

                data_folder = TEMPLATES_DATA_PATH + '/' + str(item_id) + '/'
                os.makedirs(data_folder)

                # Create preview image from uploaded file
                preview_data = request.files[template_form.preview.name].read()
                open(os.path.join(data_folder, 'preview_' + str(item_id) + '.jpg'), 'wb').write(preview_data)

                # Create zip file from uploaded file
                files_data = request.files[template_form.files.name].read()
                open(os.path.join(data_folder, 'download_' + str(item_id) + '.zip'), 'wb').write(files_data)

                return redirect('/templates/' + str(item_id))
            except Exception as e:
                print(e)
                return 'Something terrible happened.'
        else:
            return render_template('main/sell_template.html', template_form=template_form, all_tags=all_tags)
    else:
        return redirect('/login')


@mainModule.route('/sell/service', methods=['GET', 'POST'])
def sell_service():

    if session.get('user_id'):
        service_form = AddServiceForm()

        if service_form.validate_on_submit():
            try:
                item_id = items.add_service(session.get('user_id'),
                                            service_form.name.data,
                                            service_form.start_price.data,
                                            service_form.description.data,
                                            service_form.duration.data)

                return redirect('/services/' + str(item_id))
            except Exception as e:
                print(e)
                return 'Something terrible happened.'
        else:
            return render_template('main/sell_service.html', service_form=service_form)
    else:
        return redirect('/login')


@mainModule.route('/user/<string:username>')
def user_profile(username):
    user=users.get_by_username(username)
    if user is None:
        return redirect('/')

    user_id=user.user_id
    user_templates=items.get_templates_by_user_id(user_id)
    user_services=items.get_services_by_user_id(user_id)
    user_avg_rating=users.get_average_template_rating(user_id)


    return render_template('main/user.html', user=user, templates=user_templates, rating=user_avg_rating, services=user_services)

project/src/templatesandmoe/templates/main/account.html
{% extends "layout/main.html" %}

{% block title %}- Account{% endblock %}
{% block body %}
    <div class="main container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header">
                    <h3>Your Account</h3>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                <ul class="nav nav-pills nav-stacked">
                    <li class="active"><a href="{{ url_for('main.account') }}">Account</a></li>
                    <li><a href="{{ url_for('main.account_orders') }}">Orders</a></li>
                    <li><a href="{{ url_for('main.account_templates') }}">Templates</a></li>
                </ul>
            </div>

            <div class="col-md-9">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h4>Won Auctions</h4>
                    </div>
                    <div class="panel-body">
                        {% if won_bids|length > 0 %}
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <td><strong>Service</strong></td>
                                    <td><strong>Seller</strong></td>
                                    <td><strong>Amount</strong></td>
                                </tr>
                            </thead>
                            <tbody>
                                {% for bid in won_bids %}
                                    <tr>
                                        <td><a href="{{ url_for('items.single_service', item_id=bid.item_id) }}">{{ bid.name }}</a></td>
                                        <td>
                                            <a href="{{ url_for('main.user_profile', username=bid.username) }}">{{ bid.username }}</a>
                                        </td>
                                        <td>{{ currency_format(bid.amount) }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        {% else %}
                            No won bids
                        {% endif %}
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>Bidding</h4>
                    </div>
                    <div class="panel-body">
                        {% if users_bid_services|length > 0 %}
                        <table class="table">
                            <thead>
                                <tr>
                                    <td><strong>Service</strong></td>
                                    <td><strong>End date</strong></td>
                                    <td><strong>Your Bid</strong></td>
                                </tr>
                            </thead>
                            <tbody>
                                {% for service in users_bid_services %}
                                    <tr>
                                        <td><a href="{{ url_for('items.single_service', item_id=service.item_id) }}">{{ service.name }}</a></td>
                                        <td>{{ time_format(service.end_date) }}</td>
                                        <td>{{ currency_format(service.amount) }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        {% else %}
                            No current bids
                        {% endif %}
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>Your Services</h4>
                    </div>
                    <div class="panel panel-body">
                        {% if users_services|length > 0 %}
                        <table class="table">
                            <thead>
                            <tr>
                                <td><strong>Service</strong></td>
                                <td><strong># of bids</strong></td>
                                <td><strong>Highest Bid</strong></td>
                                <td><strong>End Date</strong></td>
                                <td><strong>Winner</strong></td>
                            </tr>
                            </thead>
                            <tbody>
                                {% for service in users_services %}
                                    <tr {% if service.winner is not none and service.ended == 1 %} class="success" {% endif %}>
                                        <td>
                                            <a href="{{ url_for('items.single_service', item_id=service.item_id) }}">
                                                {{ service.name }}
                                            </a>
                                        </td>
                                        <td>
                                            {{ service.bids }}
                                        </td>
                                        <td>
                                            {% if service.highest_bid is not none %}
                                                {{ currency_format(service.highest_bid) }}
                                            {% else %}
                                                No bids
                                            {% endif %}
                                        </td>
                                        <td>{{ time_format(service.end_date) }}</td>
                                        <td>
                                            {% if service.winner is not none and service.ended == 1 %}
                                                <a href="{{ url_for('main.user_profile', username=service.winner) }}">{{ service.winner }}</a>
                                            {% else %}
                                                No winner
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>


                        {% else %}
                            <div class="alert alert-info">
                                No services
                            </div>
                        {% endif %}

                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

project/src/templatesandmoe/templates/main/account_items.html
{% extends "layout/main.html" %}
{% block title %}- Account{% endblock %}
{% block body %}
    <div class="main container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header">
                    <h3>Your Templates</h3>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                <ul class="nav nav-pills nav-stacked">
                    <li><a href="{{ url_for('main.account') }}">Account</a></li>
                    <li><a href="{{ url_for('main.account_orders') }}">Orders</a></li>
                    <li class="active"><a href="{{ url_for('main.account_templates') }}">Templates</a></li>
                </ul>
            </div>

            <div class="col-md-9">
                {% if items|length > 0 %}
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <td><strong>Name</strong></td>
                                <td><strong># of Sales</strong></td>
                                <td><strong>Total Revenue</strong></td>
                            </tr>
                        </thead>
                        <tbody>
                                {% for item in items %}
                                    <tr>
                                        <td><a href="{{ url_for('items.single_template', item_id=item.item_id) }}">{{ item.name }}</a></td>
                                        <td>{{ item.sales }}</td>
                                        <td>{{ currency_format(item.revenue|default(0, true)) }}</td>
                                    </tr>
                                {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <div class="alert alert-info">
                        No templates
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

project/src/templatesandmoe/templates/main/account_orders.html
{% extends "layout/main.html" %}
{% block title %}- Account{% endblock %}
{% block body %}
    <div class="main container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-header">
                    <h3>Your Orders</h3>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                <ul class="nav nav-pills nav-stacked">
                    <li><a href="{{ url_for('main.account') }}">Account</a></li>
                    <li class="active"><a href="{{ url_for('main.account_orders') }}">Orders</a></li>
                    <li><a href="{{ url_for('main.account_templates') }}">Templates</a></li>
                </ul>
            </div>

            <div class="col-md-9">
                    {% for transaction_id, order in orders.items() %}
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <strong>Order Number: </strong>
                                <a href="{{ url_for('main.order_summary', transaction_id=hash_public_id(order['transaction_id'])) }}">
                                    {{ hash_public_id(order['transaction_id']) }}
                                </a>
                            </div>
                            <div class="panel panel-body">
                                <table class="table">
                                    <tbody>
                                        {%  for item in order['items'] %}
                                            <tr>
                                                <td class="col-md-9">
                                                    <a title="Download" class="text-success" href="{{ url_for('static', filename='templates_data/' + item.item_id|string + '/download_' + item.item_id|string + '.zip') }}">
                                                        <span class="glyphicon glyphicon-download" aria-hidden="true"></span>
                                                    </a>
                                                    <a href="{{ url_for('items.single_template', item_id=item.item_id) }}">{{ item.name }}</a>
                                                </td>
                                                <td class="col-md-3 text-right">{{ currency_format(item.price) }}</td>
                                            </tr>
                                        {% endfor %}
                                        <tr>
                                            <td class="col-md-9"><strong>Total</strong></td>
                                            <td class="col-md-3 text-right"><strong>{{ currency_format(order['total']) }}</strong></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

project/src/templatesandmoe/templates/main/order_summary.html
{% extends "layout/main.html" %}
{% block title %}- Login{% endblock %}
{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h3>Order Summary</h3>

                <p><strong>Order Number:</strong> {{ order_id }}</p>
                <p><strong>Order Placed:</strong> {{ transaction[0].created_at }}</p>

                <h4>Items</h4>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <td><strong>Item</strong></td>
                            <td><strong>Price</strong></td>
                            <td><strong>Download</strong></td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in transaction %}
                        <tr>
                            <td>{{ item.name }}</td>
                            <td>{{ item.price }}</td>
                            <td>
                                <a title="Download" class="text-success" href="{{ url_for('static', filename='templates_data/' + item.item_id|string + '/download_' + item.item_id|string + '.zip') }}">
                                    <span class="glyphicon glyphicon-download" aria-hidden="true"></span>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                        <tr>
                            <td><strong>Total</strong></td>
                            <td>{{ transaction[0].total }}</td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-md-4">
                <h3>Payment Details</h3>
                <p><strong>Name:</strong> {{ transaction[0].card_name }}</p>
                <p><strong>Number: </strong> {{ transaction[0].card_number }}</p>
            </div>
        </div>
    </div>
{% endblock %}